# Generated by Django 5.2.5 on 2025-09-04 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_rayon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('pk', models.CompositePrimaryKey('refProd', 'idRayon', blank=True, editable=False, primary_key=True, serialize=False)),
                ('qte', models.IntegerField()),
                ('idRayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monApp.rayon')),
                ('refProd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monApp.produit')),
            ],
        ),
    ]
