# Generated by Django 5.2.5 on 2025-09-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_contenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dateFabProd',
            field=models.DateField(blank=True, null=True),
        ),
    ]
