# Generated by Django 5.2.5 on 2025-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0004_produit_datefabprod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idStatus', models.AutoField(primary_key=True, serialize=False)),
                ('libelleStatus', models.CharField(max_length=100)),
            ],
        ),
    ]
